import React, { createContext, useContext, useState } from "react";

type Language = "en" | "el";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language;
    return saved || "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

const translations = {
      en: {
        "welcome_back": "Welcome back,",
        "your_property": "Your Property",
        "apt": "Apt.",
        "floor": "Floor",
        "due_amount": "Due Amount",
        "due_date": "Due Date",
        "statements": "Statements",
        "history": "History",
        "recent_expenses": "Recent Expenses",
        "see_all": "See All",
        "expenses": "Expenses",
        "add_expense": "New Expense",
        "profile": "Profile",
        "search_expenses": "Search expenses...",
        "all": "All",
        "utilities": "Utilities",
        "maintenance": "Maintenance",
        "cleaning": "Cleaning",
        "insurance": "Insurance",
        "view_invoice": "View Invoice",
        "scan_invoice": "Scan Invoice",
        "ai_will_extract": "AI will extract supplier & amount",
        "camera": "Camera",
        "upload": "Upload",
        "analyzing": "Analyzing Document...",
        "scan_complete": "Scan Complete",
        "scan_again": "Scan Again",
        "supplier_name": "Supplier Name",
        "amount": "Amount (€)",
          "date": "Date",
          "time": "Time",
          "category": "Category",
        "notes": "Notes (Optional)",
        "additional_details": "Additional details...",
        "save_expense": "Save Expense",
        "personal_information": "Personal Information",
        "notifications": "Notifications",
        "security_privacy": "Security & Privacy",
        "app_settings": "App Settings",
        "help_support": "Help & Support",
        "log_out": "Log Out",
        "monthly_statements": "Monthly Statements",
        "paid": "Paid",
        "pdf": "PDF",
        "total_expenses": "Total Expenses",
        "past_30_days": "Past 30 days",
        "your_share": "Your Share",
        "based_on": "Based on",
        "transactions": "Transactions",
        "expense_recorded": "Expense Recorded",
        "expense_allocated": "The expense has been allocated to apartments.",
        "resident": "Resident",
        "manager": "Manager",
        "phone_number": "Phone Number",
        "email_address": "Email Address",
        "continue": "Continue",
        "or": "OR EMAIL",
        "terms_privacy": "By continuing, you agree to our Terms of Service & Privacy Policy.",
        "welcome": "Welcome",
        "terms_agree": "By continuing, you agree to our Terms of Service & Privacy Policy.",
        "owner": "Owner",
        "tenant": "Tenant",
        "payer": "Payer",
        "select_payer": "Select Payer",
        "pallade_building": "Pallade Building A",
        "elevator_maintenance": "Elevator Maintenance",
        "cleaning_service": "Cleaning Service",
        "water_supply": "Water Supply",
        "nov_statement": "November Statement Paid",
        "english": "English",
        "greek": "Greek",
        "language": "Language",
        "november": "November",
        "december": "December",
        "october": "October",
        "september": "September",
          "august": "August",
          "verify_phone": "Verify Phone",
          "otp_sent_to": "OTP sent to",
          "verify": "Verify",
          "resend_in": "Resend in",
          "resend_code": "Resend Code",
          "subscription": "Subscription",
          "subscription_status": "Subscription Status",
          "active": "Active",
          "expired": "Expired",
          "no_subscription": "No Subscription",
          "pending": "Pending",
          "canceled": "Canceled",
          "purchase_subscription": "Purchase Subscription",
          "renew_subscription": "Renew Subscription",
          "cancel_subscription": "Cancel Subscription",
          "subscription_price": "€29.99/month",
          "subscription_description": "Access all manager features",
          "valid_until": "Valid until",
          "processing_payment": "Processing payment...",
          "payment_successful": "Payment successful!",
            "payment_failed": "Payment failed. Please try again.",
            "subscription_features": "Everything you need to manage your building",
            "feature_automated_expenses": "Automated Expense Tracking",
            "feature_monthly_statements": "Monthly Statement Generation",
            "feature_tenant_portal": "Tenant & Owner Portals",
            "feature_priority_support": "Priority Customer Support",
              "feature_ai_scanning": "AI Invoice Scanning",
              "apartment": "Apartment",
              "common_expense": "Common Expense",
              "select_apartment": "Select Apartment",
            },
          el: {
        "welcome_back": "Καλώς ήρθατε πίσω,",
        "your_property": "Η Περιουσία Σας",
        "apt": "Διαμ.",
        "floor": "Ορόφ.",
        "due_amount": "Ποσό που Οφείλεται",
        "due_date": "Ημερομηνία Λήξης",
        "statements": "Δηλώσεις",
        "history": "Ιστορικό",
        "recent_expenses": "Πρόσφατες Δαπάνες",
        "see_all": "Δείτε Όλα",
        "expenses": "Δαπάνες",
        "add_expense": "Νέα Δαπάνη",
        "profile": "Προφίλ",
        "search_expenses": "Αναζήτηση δαπανών...",
        "all": "Όλα",
        "utilities": "Υπηρεσίες",
        "maintenance": "Συντήρηση",
        "cleaning": "Καθαρισμός",
        "insurance": "Ασφάλεια",
        "view_invoice": "Προβολή Τιμολογίου",
        "scan_invoice": "Σάρωση Τιμολογίου",
        "ai_will_extract": "Η AI θα εξάγει προμηθευτή και ποσό",
        "camera": "Κάμερα",
        "upload": "Μεταφόρτωση",
        "analyzing": "Ανάλυση Εγγράφου...",
        "scan_complete": "Η Σάρωση Ολοκληρώθηκε",
        "scan_again": "Σάρωση Ξανά",
        "supplier_name": "Όνομα Προμηθευτή",
        "amount": "Ποσό (€)",
        "date": "Ημερομηνία",
        "time": "Ώρα",
        "category": "Κατηγορία",
        "notes": "Σημειώσεις (Προαιρετικό)",
        "additional_details": "Πρόσθετες λεπτομέρειες...",
        "save_expense": "Αποθήκευση Δαπάνης",
        "personal_information": "Προσωπικές Πληροφορίες",
        "notifications": "Ειδοποιήσεις",
        "security_privacy": "Ασφάλεια & Ιδιωτικότητα",
        "app_settings": "Ρυθμίσεις Εφαρμογής",
        "help_support": "Βοήθεια & Υποστήριξη",
        "log_out": "Αποσύνδεση",
        "monthly_statements": "Μηνιαίες Δηλώσεις",
        "paid": "Πληρώθηκε",
        "pdf": "PDF",
        "total_expenses": "Σύνολο Δαπανών",
        "past_30_days": "Τελευταίες 30 μέρες",
        "your_share": "Το Μερίδιό Σας",
        "based_on": "Βάσει",
        "transactions": "Συναλλαγές",
        "expense_recorded": "Δαπάνη Καταγράφηκε",
        "expense_allocated": "Η δαπάνη έχει κατανεμηθεί σε διαμερίσματα.",
        "resident": "Κάτοικος",
        "manager": "Διαχειριστής",
        "phone_number": "Αριθμός Τηλεφώνου",
        "email_address": "Διεύθυνση Email",
        "continue": "Συνέχεια",
        "or": "Ή EMAIL",
        "terms_privacy": "Συνεχίζοντας, συμφωνείτε με τους Όρους Υπηρεσίας & Πολιτική Ιδιωτικότητας.",
        "welcome": "Καλώς ήρθατε",
        "owner": "Ιδιοκτήτης",
        "tenant": "Ενοικιαστής",
        "payer": "Πληρωτής",
        "select_payer": "Επιλογή Πληρωτή",
        "pallade_building": "Κτίριο Pallade A",
        "elevator_maintenance": "Συντήρηση Ανελκυστήρα",
        "cleaning_service": "Υπηρεσία Καθαρισμού",
        "water_supply": "Παροχή Νερού",
        "nov_statement": "Δήλωση Νοεμβρίου Πληρώθηκε",
        "english": "Αγγλικά",
        "greek": "Ελληνικά",
        "language": "Γλώσσα",
        "november": "Νοέμβριος",
        "december": "Δεκέμβριος",
        "october": "Οκτώβριος",
        "september": "Σεπτέμβριος",
        "august": "Αύγουστος",
        "verify_phone": "Επαλήθευση Τηλεφώνου",
        "otp_sent_to": "Ο κωδικός OTP στάλθηκε στο",
        "verify": "Επαλήθευση",
        "resend_in": "Επαναποστολή σε",
        "resend_code": "Επαναποστολή Κωδικού",
          "subscription": "Συνδρομή",
          "subscription_status": "Κατάσταση Συνδρομής",
          "active": "Ενεργή",
          "expired": "Έληξε",
          "no_subscription": "Χωρίς Συνδρομή",
          "pending": "Σε Εκκρεμότητα",
          "canceled": "Ακυρωμένη",
          "purchase_subscription": "Αγορά Συνδρομής",
          "renew_subscription": "Ανανέωση Συνδρομής",
          "cancel_subscription": "Ακύρωση Συνδρομής",
          "subscription_price": "€29.99/μήνα",
          "subscription_description": "Πρόσβαση σε όλες τις λειτουργίες διαχειριστή",
          "valid_until": "Ισχύει έως",
          "processing_payment": "Επεξεργασία πληρωμής...",
          "payment_successful": "Επιτυχής πληρωμή!",
            "payment_failed": "Η πληρωμή απέτυχε. Παρακαλώ δοκιμάστε ξανά.",
            "subscription_features": "Όλα όσα χρειάζεστε για τη διαχείριση του κτιρίου σας",
            "feature_automated_expenses": "Αυτοματοποιημένη Παρακολούθηση Δαπανών",
            "feature_monthly_statements": "Μηνιαία Έκδοση Κοινοχρήστων",
            "feature_tenant_portal": "Πύλη Ενοίκων & Ιδιοκτητών",
            "feature_priority_support": "Προτεραιότητα στην Υποστήριξη",
              "feature_ai_scanning": "AI Σάρωση Τιμολογίων",
              "apartment": "Διαμέρισμα",
              "common_expense": "Κοινόχρηστη Δαπάνη",
              "select_apartment": "Επιλογή Διαμερίσματος",
            },
      };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
